### ISSUE TITLE
Add animations to individual elements

### ISSUE THREAD

**Issue by a-trost** [a-trost/newhavenio#16]
The Gatsby Starter came with Pose and an Intersection Observer example that we can use.

Subtle entry animations would add a level of polish to the site. 

Might be a good use case for a reusable Higher Order component that wraps elements to animate in on scroll.

Pose Docs: https://popmotion.io/pose/
Intersection observer: https://github.com/a-trost/newhavenio/tree/master/src/components/io

**Comment by timhwang21** [comment]
I think this is nice but I'm wary of overuse. I think animations can look cheap if they're too intrusive. 

I sort of think our page transition animation should be faster and/or more subtle. (I also removed the navbar animation since I thought it was silly to animate entry/exit of a component that didn't significantly change.)

**Comment by a-trost** [comment]
Totally agree. Should define this more specifically. And the nav animation was definitely silly.

**Comment by Quinncuatro** [comment]
> I'm wary of overuse

Could be missing something, but does this have any animation beyond the header un-hiding on scroll?

**Comment by timhwang21** [comment]
It did but I removed it in my latest changes

**Comment by Quinncuatro** [comment]
Word.

**Comment by timhwang21** [comment]
FWIW, I swapped out Pose for Framer Motion (the successor to Pose), and have already added some basic animations. To reuse we can just pull out a config object and spread them into props -- a lot simpler than a HOC.

Closing this for now, we can easily add more animations on an ad hoc basis.
